### ISSUE TITLE
Use GitHub semantics

### ISSUE THREAD

**Issue by J2ZROMERO** [Haywayaheadshot/songkick-CCGlobal-web-design#2]
## **Bug description and solution**
- Try to use GitHub syntax to grab your link  [Semantics](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). code line from 16 to 23.

**Comment by Haywayaheadshot** [comment]
> ## **Bug description and solution**
> * Try to use GitHub syntax to grab your link  [Semantics](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). code line from 16 to 23.

Thank you @J2ZROMERO. I have done it
